### ISSUE TITLE
ERROR: pull access denied for janusgatewaydocker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by zefredzocohen** [canyanio/janus-gateway-docker#19]
![image](https://user-images.githubusercontent.com/6443703/123505061-22efc500-d687-11eb-99ff-5d7c68fa25a2.png)
When I run docker-compose up with docker-compose file 
```
version: '2.1'
services:

  #
  # janus-gateway
  #
  janus-gateway:
    image: 'canyan/janus-gateway:0.10.7'
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
    volumes:
      - "./etc/janus/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
      - "./etc/janus/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg"
    restart: always
```
, I get error `ERROR: pull access denied for janusgatewaydocker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`. 

Does anyone have a solution to this problem?
