### ISSUE TITLE
How can I checkout to another branch of janus?

### ISSUE THREAD

**Issue by algosoftbd** [canyanio/janus-gateway-docker#23]
Hello,
I modified the `docker-compose.yml` file like this:

```
version: '2.1'
services:

  janus-gateway:
    image: 'canyan/janus-gateway:0.10.7'
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "8188:8188"
      - "8088:8088"
      - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
      - "20000-20500:20000-20500/udp"
    environment:
      - GIT_BRANCH=multistream
    volumes:
      - "./janus-configs/:/usr/local/etc/janus/"
```

Here I mentioned `GIT_BRANCH=multistream`. But, it seems `multistream` branch is not running in my docker container. I killed the previous docker image and run `docker-compose up -d` again though. How can I check this and ensure that specific branch of janus is running?
